# Generated by Django 5.1.6 on 2025-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256, verbose_name='User Name')),
                ('client_email', models.CharField(max_length=256, unique=True, verbose_name='E-mail User')),
                ('client_number', models.CharField(max_length=256, verbose_name='Number User')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
