# Generated by Django 5.2.4 on 2025-08-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=256, verbose_name='Name of Employee')),
                ('employee_email', models.EmailField(max_length=256, unique=True, verbose_name='E-mail of Employee')),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='Number of Employee')),
                ('employee_cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF of Employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
