# Generated by Django 5.2.4 on 2025-08-04 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_client_email_alter_client_client_name_and_more'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do Agendamento')),
                ('time', models.TimeField(verbose_name='Hora do Agendamento')),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=20, verbose_name='Status do Agendamento')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulings', to='client.client', verbose_name='Cliente')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedulings', to='employee.employee', verbose_name='Profissional')),
            ],
            options={
                'db_table': 'scheduling',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Agendado')), fields=('client',), name='unique_scheduling_per_client')],
            },
        ),
    ]
