# Generated by Django 5.2.4 on 2025-08-04 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_service', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='salon_service',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='schedulings', to='salon_service.salonservice', verbose_name='Serviço'),
            preserve_default=False,
        ),
    ]
