# Generated by Django 5.2.4 on 2025-08-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_client_email_alter_client_client_name_and_more'),
        ('employee', '0001_initial'),
        ('salon_service', '0001_initial'),
        ('scheduling', '0002_scheduling_salon_service'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduling',
            name='unique_scheduling_per_client',
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Concluído', 'Concluído'), ('Executando', 'Executando'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=20, verbose_name='Status do Agendamento'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='time',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AddConstraint(
            model_name='scheduling',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Concluído', 'Cancelado']), _negated=True), fields=('client',), name='unique_active_scheduling_per_client'),
        ),
    ]
