# Generated by Django 5.2.4 on 2025-08-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(max_length=256, verbose_name='Name of service')),
                ('value_of_service', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Value of service')),
            ],
            options={
                'db_table': 'salon_service',
            },
        ),
    ]
