# Generated by Django 5.2.4 on 2025-08-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=256, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número do Cliente'),
        ),
    ]
